/**
 * phrases.js  -  the fixed, non-model content and interface copy.
 *
 * Nothing here is ever generated by the model. That is deliberate: the calm
 * "verify with a number you look up yourself" guidance must be impossible for
 * a scammer (or a hijacked model) to suppress or rewrite.
 *
 * Spec ref: spec.md > Components > phrases.js
 * PRD ref:  prd.md > General scam phrases (always visible), prd.md > Phone-number guidance
 */

/** The always-visible awareness list. Same for everyone, on every message. */
export const GENERAL_PHRASES = [
  {
    say: '"Act now - this offer expires today."',
    why: 'Real businesses rarely need you to decide in the next few minutes.'
  },
  {
    say: '"Your account has been locked / suspended."',
    why: 'Banks and services do not usually announce this by text and then ask you to "verify."'
  },
  {
    say: '"We have noticed suspicious activity. Confirm your details."',
    why: 'The real version of this message never asks for your password, PIN, or codes.'
  },
  {
    say: '"Your package is held. Pay a small redelivery fee."',
    why: 'A tiny fee is the hook - it is there to get your card details.'
  },
  {
    say: '"You have been selected / you have won."',
    why: 'You do not have to pay or give details to receive a real prize.'
  },
  {
    say: '"Please keep this between us."',
    why: 'Secrecy protects the scammer, not you. Real organizations do not ask for it.'
  },
  {
    say: '"You are in trouble / there is a warrant / you owe money."',
    why: 'Fear is the tool. It is designed to stop you checking.'
  },
  {
    say: '"I am from the fraud team - read me the code you just got."',
    why: 'That code proves it is you. Nobody legitimate will ever ask you to read it out.'
  }
];

/** Fixed copy - the calm next step. Always shown with a result. Cannot be model output. */
export const NEXT_STEP_TEXT =
  'There is no rush, no matter what the message says. Do not reply, do not click, and do not send money or codes. ' +
  'If it mentions an account, a payment, or a refund, look up the company\'s number yourself - on their website, ' +
  'or the number on the back of your card - and call that one. You are allowed to take your time.';

/**
 * Independent-verification guidance. Shown when a message pushes a phone number
 * (spec.md > The Result Shape - never gated *only* on the model's boolean; app.js
 * also re-checks the raw text for number patterns, and that check requires an
 * actual number so this box does not appear on messages that do not mention one).
 */
export const PHONE_GUIDANCE_TEXT =
  'Some scams copy real logos, email addresses, and phone numbers perfectly. The only number you can trust is ' +
  'one you look up yourself - check the company\'s own website, your bank card, or your account statement, and ' +
  'call that number. Never call or message a number that came in the message itself.';

/** Error-state copy, mapped from the error codes in api.js. */
export const ERROR_COPY = {
  NO_KEY:
    'First Defense needs a key to reach the language model that does the reading. ' +
    'Nothing you paste is sent anywhere without one.',
  NETWORK:
    'The service that reads the message did not answer just now. This is usually a connection problem - ' +
    'please try again in a moment.',
  OFF_SHAPE:
    'The reading came back in a form this page could not use, so nothing is being shown. ' +
    'Rather than risk a confusing or wrong summary, we stop here.',
  EMPTY:
    'There was no message to look at. Paste the text you received, then try again.'
};

/**
 * The no-ask case. Stated plainly, with NO reassurance about the message itself.
 * Kept for compatibility; the live UI builds its own version of this copy.
 */
export const NO_ASK_TEXT =
  'This message does not clearly ask you to do anything - no money, no link, no details, no call. ' +
  'That does not make it safe or unsafe. If it still feels off, treat it the same way: do not reply, ' +
  'and verify with the company using a number you find yourself.';

/** The empty-tactics case. Again: no reassurance either way. */
export const NO_TACTICS_TEXT = 'This message does not lean on the usual pressure tactics. It can still be a scam.';

/** A clearly-labeled sample breakdown, used only as a fallback demonstration. */
export const SAMPLE_RESULT = {
  ask: 'They want you to call the number in the message and give them your account details.',
  tactics: [
    { name: 'Urgency', explanation: 'It says you must act within 24 hours, so you decide before you can check.' },
    { name: 'Fear', explanation: 'It threatens to lock your account and freeze your money if you do not comply.' },
    { name: 'Authority', explanation: 'It pretends to be an official fraud or support team watching your account.' }
  ],
  similarScams: ['Bank fraud-alert phone scam', 'Fake customer-service identity check'],
  pushesPhoneNumber: true
};
